### PR TITLE
PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by animaux**

### CODE REVIEW

**Review by ahwayakchih — APPROVED** [review]
Thanks!

**Comment by animaux** [comment]
No worries :) I was surprised it worked so well considering it’s age!

**Comment by ahwayakchih** [comment]
Yeah, it's good that Symphony's API did not change that much :).

**Comment by animaux** [comment]
Nothing much changes anymore at all recently … `:/`

**Comment by ahwayakchih** [comment]
It looks like there was v3.0 prepared https://github.com/symphonycms/symphonycms/commit/ea690f74cbc5b325014e45fb44b7ad5501b7da5e but not released/announced. Looks like quite a lot was changed under the hood https://github.com/symphonycms/symphonycms/commit/e8af4536c5e5fc26e162e82fd8b3e8a548801a4b

**Comment by animaux** [comment]
3.0.0 is kind of the official version now, but has some bugs, not to mention extension compatibility. 2.7.10 has some nasty bugs too. Nicholas was the only person really maintaining the codebase, but since march it’s all tumbleweed, sadly.

**Comment by ahwayakchih** [comment]
Ah, that's too bad. Did his company switch to some other CMS? Maybe Symphony users should start a bounty-like thing to support the project (or per-bug/feature tasks)?

**Comment by animaux** [comment]
I wonder. They do have a repository with a craft-template … 

There were some paid initiatives, like the associations interface. But probably too many loose ends currently, plus the everlasting problem of documentation.

**Comment by ahwayakchih** [comment]
IIRC documentation in form of easy to read web pages was lacking, but code was either commented well enough, or simple enough to follow to find things out.

I guess XML/XSLT is even less popular now, then it was back when i developed sites with Symphony :(. I still prefer its ideas (mini-core, flexible types, templating, etc...). I think it would be even better if administration pages were built the same way as fronted was supposed to be created. That way it would serve as a perfect example for newcomers, and would make it easy to modify admin pages for any type of site (and users).

**Comment by animaux** [comment]
The one thing I’ve always missed was an in-depth-tutorial on building extensions, and custom datasources. I’ve only come this far with my limited programming knowledge and reverse engineering.

I think the idea to build the backend with the frontend-engine at some point, but never realised.

Symphony Newcomers … sounds like RSS `;)`

**Comment by ahwayakchih** [comment]
:)

**Pull request merged**
